"""add Transportation Order model

Revision ID: 068a4fbf044a
Revises: aac8bdb7d9a3
Create Date: 2024-05-14 13:29:13.744300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '068a4fbf044a'
down_revision = 'aac8bdb7d9a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transportation_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('trailer_type', sa.String(length=16), nullable=False),
    sa.Column('load_weight', sa.Integer(), nullable=False),
    sa.Column('loading_place', sa.Integer(), nullable=False),
    sa.Column('delivery_place', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_place'], ['company.id'], ),
    sa.ForeignKeyConstraint(['loading_place'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transportation_order')
    # ### end Alembic commands ###
