"""change DateTime to Date for creation_date field in TransportationOrder model

Revision ID: 763bbcfe1674
Revises: 02a06dc2834a
Create Date: 2024-06-01 12:23:10.203327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '763bbcfe1674'
down_revision = '02a06dc2834a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transportation_order', schema=None) as batch_op:
        batch_op.alter_column('creation_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transportation_order', schema=None) as batch_op:
        batch_op.alter_column('creation_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
