"""add max_load_capacity field for Trailer model

Revision ID: a3e1a900cfe7
Revises: ff08eefa3f0d
Create Date: 2024-06-13 10:44:15.817268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3e1a900cfe7'
down_revision = 'ff08eefa3f0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trailer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_load_capacity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trailer', schema=None) as batch_op:
        batch_op.drop_column('max_load_capacity')

    # ### end Alembic commands ###
