"""add Company model table

Revision ID: aac8bdb7d9a3
Revises: 2bc926cd8674
Create Date: 2024-05-13 15:42:34.883867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aac8bdb7d9a3'
down_revision = '2bc926cd8674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=32), nullable=False),
    sa.Column('country', sa.String(length=32), nullable=False),
    sa.Column('town', sa.String(length=32), nullable=False),
    sa.Column('postal_code', sa.String(length=16), nullable=False),
    sa.Column('street', sa.String(length=32), nullable=False),
    sa.Column('street_number', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company')
    # ### end Alembic commands ###
