"""add unique field for registration numbers in TractorHead and Trailer models

Revision ID: b51c4cbe6ebf
Revises: f90b50c778c2
Create Date: 2024-05-26 09:26:51.538632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b51c4cbe6ebf'
down_revision = 'f90b50c778c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tractor_head', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_tractor_head_registration_number', ['registration_number'])

    with op.batch_alter_table('trailer', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_trailer_registration_number', ['registration_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trailer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('tractor_head', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
