"""empty message

Revision ID: e91e4c914fe7
Revises: 068a4fbf044a
Create Date: 2024-05-17 13:00:07.123109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e91e4c914fe7'
down_revision = '068a4fbf044a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transportation_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver', sa.String(), nullable=True))
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.create_foreign_key('fk_transportation_order_driver', 'user', ['driver'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transportation_order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('driver')

    # ### end Alembic commands ###
